# Generated by Django 5.1 on 2024-09-05 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_changed_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='consumable/images', verbose_name='изображение')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'расходный материал',
                'verbose_name_plural': 'расходные материалы',
                'ordering': ('price',),
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
