# Generated by Django 5.1 on 2024-08-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_manufactured_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufactured_at',
            new_name='manufactured_at2',
        ),
    ]
