# Generated by Django 5.1 on 2024-09-05 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_equipment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('price',), 'verbose_name': 'техника', 'verbose_name_plural': 'техника'},
        ),
    ]
