# Generated by Django 5.1 on 2024-09-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumable',
            options={'ordering': ('price', 'purchases_count'), 'verbose_name': 'расходный материал', 'verbose_name_plural': 'расходные материалы'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('price', 'purchases_count'), 'verbose_name': 'техника', 'verbose_name_plural': 'техника'},
        ),
        migrations.AddField(
            model_name='consumable',
            name='purchases_count',
            field=models.IntegerField(default=0, verbose_name='единиц куплено'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchases_count',
            field=models.IntegerField(default=0, verbose_name='единиц куплено'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='guarantee',
            field=models.CharField(max_length=100, verbose_name='гарантия'),
        ),
    ]
