# Generated by Django 5.1 on 2024-09-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_consumable_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
