# Generated by Django 5.1 on 2024-09-18 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='номер версии')),
                ('name', models.CharField(max_length=150, verbose_name='название версии')),
                ('is_current_version', models.BooleanField(default=True, verbose_name='активность версии')),
                ('consumable_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.consumable', verbose_name='продукт расходник')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
                'ordering': ('number', 'name'),
            },
        ),
    ]
