# Generated by Django 4.2.2 on 2024-09-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_consumable_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumable',
            options={'ordering': ('price', 'purchases_count'), 'permissions': [('set_published', 'Can set publication status of product'), ('change_description', 'Can change description of product'), ('change_category', 'Can change category of product')], 'verbose_name': 'расходный материал', 'verbose_name_plural': 'расходные материалы'},
        ),
        migrations.AddField(
            model_name='consumable',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='признак публикации'),
        ),
    ]
